# Generated by Django 5.2.6 on 2025-10-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ojs_notice_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID Aviso OJS"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Descripción corta"
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "cpv_codes",
                    models.JSONField(default=list, verbose_name="Códigos CPV"),
                ),
                (
                    "nuts_regions",
                    models.JSONField(default=list, verbose_name="Regiones NUTS"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("services", "Servicios"),
                            ("supplies", "Suministros"),
                            ("works", "Obras"),
                        ],
                        default="services",
                        max_length=50,
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        max_length=300, verbose_name="Organismo contratante"
                    ),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de organismo"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "tender_deadline_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha límite de oferta"
                    ),
                ),
                (
                    "tender_deadline_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora límite"),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("restricted", "Restringido"),
                            ("negotiated", "Negociado"),
                            ("competitive_dialogue", "Diálogo competitivo"),
                        ],
                        default="open",
                        max_length=50,
                        verbose_name="Tipo de procedimiento",
                    ),
                ),
                (
                    "award_criteria",
                    models.JSONField(
                        default=dict, verbose_name="Criterios de adjudicación"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contacto"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono de contacto"
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(blank=True, verbose_name="URL de contacto"),
                ),
                (
                    "xml_content",
                    models.TextField(blank=True, verbose_name="Contenido XML original"),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta del archivo XML"
                    ),
                ),
                (
                    "xpaths_used",
                    models.JSONField(default=dict, verbose_name="XPaths utilizados"),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Indexado en"
                    ),
                ),
                ("views_count", models.IntegerField(default=0, verbose_name="Vistas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Licitación",
                "verbose_name_plural": "Licitaciones",
                "ordering": ["-publication_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ojs_notice_id"], name="tenders_ten_ojs_not_55966b_idx"
                    ),
                    models.Index(
                        fields=["-publication_date"],
                        name="tenders_ten_publica_750081_idx",
                    ),
                    models.Index(
                        fields=["-deadline"], name="tenders_ten_deadlin_926963_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedTender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interesado"),
                            ("applied", "Oferta presentada"),
                            ("won", "Ganada"),
                            ("lost", "Perdida"),
                        ],
                        default="interested",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recordatorio"
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Guardado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_tenders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="tenders.tender",
                        verbose_name="Licitación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licitación guardada",
                "verbose_name_plural": "Licitaciones guardadas",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "tender")},
            },
        ),
        migrations.CreateModel(
            name="TenderRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_total", models.FloatField(verbose_name="Score total")),
                ("score_technical", models.FloatField(verbose_name="Score técnico")),
                ("score_budget", models.FloatField(verbose_name="Score presupuesto")),
                (
                    "score_geographic",
                    models.FloatField(verbose_name="Score geográfico"),
                ),
                (
                    "score_experience",
                    models.FloatField(verbose_name="Score experiencia"),
                ),
                (
                    "score_competition",
                    models.FloatField(verbose_name="Score competencia"),
                ),
                (
                    "probability_success",
                    models.FloatField(verbose_name="Probabilidad de éxito"),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        default=list, verbose_name="Razones de compatibilidad"
                    ),
                ),
                (
                    "warning_factors",
                    models.JSONField(
                        default=list, verbose_name="Factores de advertencia"
                    ),
                ),
                (
                    "recommendation_level",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        max_length=10,
                        verbose_name="Nivel de recomendación",
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(
                        default=dict, verbose_name="Información de contacto"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Generado en"),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="tenders.tender",
                        verbose_name="Licitación",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación de licitación",
                "verbose_name_plural": "Recomendaciones de licitaciones",
                "ordering": ["-score_total", "-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-score_total"],
                        name="tenders_ten_user_id_86c1fb_idx",
                    )
                ],
                "unique_together": {("user", "tender")},
            },
        ),
    ]
