# Generated by Django 5.0.14 on 2025-12-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Identifiant unique de l'expédition (ex: EXP-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "nom_article",
                    models.CharField(
                        help_text="Nom descriptif du produit",
                        max_length=255,
                        verbose_name="Nom de l'article",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du produit",
                        verbose_name="Description",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("FR_DZ", "France → Algérie"),
                            ("DZ_FR", "Algérie → France"),
                        ],
                        default="FR_DZ",
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("erreur", "Erreur"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "etape_courante",
                    models.IntegerField(
                        default=1,
                        help_text="Numéro de l'étape en cours (1-5)",
                        verbose_name="Étape courante",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expeditions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expédition",
                "verbose_name_plural": "Expéditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpeditionEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        choices=[
                            (1, "Classification Douanière"),
                            (2, "Génération Documents"),
                            (3, "Transmission Électronique"),
                            (4, "Paiement des Droits"),
                            (5, "Gestion OEA"),
                        ],
                        verbose_name="Numéro d'étape",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("erreur", "Erreur"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Résultats et données de l'étape (JSON)",
                        verbose_name="Données",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="expeditions.expedition",
                        verbose_name="Expédition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape d'expédition",
                "verbose_name_plural": "Étapes d'expédition",
                "ordering": ["expedition", "numero"],
                "unique_together": {("expedition", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ExpeditionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo du produit"),
                            ("fiche_technique", "Fiche technique"),
                            ("dau", "DAU - Document Administratif Unique"),
                            ("d10", "Formulaire D10"),
                            ("d12", "Formulaire D12"),
                            ("ens", "ENS - Entry Summary Declaration"),
                            ("certificat_origine", "Certificat d'origine"),
                            ("autre", "Autre document"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="expeditions/documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "nom_original",
                    models.CharField(
                        help_text="Nom du fichier tel qu'uploadé",
                        max_length=255,
                        verbose_name="Nom original",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="expeditions.expedition",
                        verbose_name="Expédition",
                    ),
                ),
                (
                    "etape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="expeditions.expeditionetape",
                        verbose_name="Étape associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'expédition",
                "verbose_name_plural": "Documents d'expédition",
                "ordering": ["-created_at"],
            },
        ),
    ]
