# Generated by Django 5.1.6 on 2025-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expeditiondocument",
            options={
                "ordering": ["type", "ordre", "-created_at"],
                "verbose_name": "Document d'expédition",
                "verbose_name_plural": "Documents d'expédition",
            },
        ),
        migrations.AddField(
            model_name="expeditiondocument",
            name="ordre",
            field=models.IntegerField(
                default=0,
                help_text="Ordre d'affichage du document",
                verbose_name="Ordre",
            ),
        ),
    ]
