# Generated by Django 5.1.6 on 2025-12-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0002_add_ordre_to_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifie le"),
                ),
                (
                    "expedition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_chat",
                        to="expeditions.expedition",
                        verbose_name="Expedition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat de classification",
                "verbose_name_plural": "Chats de classification",
            },
        ),
        migrations.CreateModel(
            name="ClassificationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("assistant", "Assistant"),
                            ("system", "Systeme"),
                        ],
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informations supplementaires (tools utilisees, tokens, etc.)",
                        verbose_name="Metadonnees",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="expeditions.classificationchat",
                        verbose_name="Chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de classification",
                "verbose_name_plural": "Messages de classification",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TARICProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_sh",
                    models.CharField(max_length=6, verbose_name="Code SH (6 chiffres)"),
                ),
                (
                    "code_nc",
                    models.CharField(max_length=8, verbose_name="Code NC (8 chiffres)"),
                ),
                (
                    "code_taric",
                    models.CharField(
                        max_length=10, verbose_name="Code TARIC (10 chiffres)"
                    ),
                ),
                (
                    "probability",
                    models.FloatField(verbose_name="Probabilite/Precision (%)"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("justification", models.TextField(verbose_name="Justification")),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="Selectionne"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="expeditions.classificationmessage",
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition TARIC",
                "verbose_name_plural": "Propositions TARIC",
                "ordering": ["-probability"],
            },
        ),
    ]
