# Generated by Django 5.1.6 on 2026-01-06 10:46

import apps.expeditions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0004_refactor_etapes_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expedition', 'verbose_name_plural': 'Expeditions'},
        ),
        migrations.AlterModelOptions(
            name='expeditionetape',
            options={'ordering': ['expedition', 'numero'], 'verbose_name': "Etape d'expedition", 'verbose_name_plural': "Etapes d'expedition"},
        ),
        migrations.AlterField(
            model_name='expedition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.TextField(blank=True, help_text='Description detaillee du produit', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='direction',
            field=models.CharField(choices=[('FR_DZ', 'France -> Algerie'), ('DZ_FR', 'Algerie -> France')], default='FR_DZ', max_length=10, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='etape_courante',
            field=models.IntegerField(default=1, help_text="Numero de l'etape en cours (1-5)", verbose_name='Etape courante'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(help_text="Identifiant unique de l'expedition (ex: EXP-2025-001)", max_length=50, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('erreur', 'Erreur')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifie le'),
        ),
        migrations.AlterField(
            model_name='expeditiondocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='expeditiondocument',
            name='nom_original',
            field=models.CharField(help_text="Nom du fichier tel qu'uploade", max_length=255, verbose_name='Nom original'),
        ),
        migrations.AlterField(
            model_name='expeditionetape',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termine le'),
        ),
        migrations.AlterField(
            model_name='expeditionetape',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='expeditions.expedition', verbose_name='Expedition'),
        ),
        migrations.AlterField(
            model_name='expeditionetape',
            name='numero',
            field=models.IntegerField(choices=[(1, 'Classification Douaniere'), (2, 'Generation Documents'), (3, 'Transmission Electronique'), (4, 'Paiement des Droits'), (5, 'Gestion OEA')], verbose_name="Numero d'etape"),
        ),
        migrations.AlterField(
            model_name='expeditionetape',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='WebDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_origen', models.URLField(help_text='URL desde donde se descargo el documento', max_length=2000, verbose_name='URL de origen')),
                ('titulo', models.CharField(help_text='Titulo o descripcion del documento', max_length=255, verbose_name='Titulo')),
                ('fichier', models.FileField(upload_to=apps.expeditions.models.web_document_upload_path, verbose_name='Fichier')),
                ('nom_fichier', models.CharField(help_text='Nombre del archivo guardado', max_length=255, verbose_name='Nom du fichier')),
                ('razon_guardado', models.TextField(blank=True, help_text='Por que el agente considero util guardar este documento', verbose_name='Razon de guardado')),
                ('texto_extraido', models.TextField(blank=True, help_text='Preview del texto extraido del PDF', verbose_name='Texto extraido')),
                ('tamano_bytes', models.IntegerField(default=0, verbose_name='Tamano en bytes')),
                ('paginas', models.IntegerField(default=0, verbose_name='Numero de paginas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Descargado el')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_documents', to='expeditions.expeditionetape', verbose_name='Etape')),
            ],
            options={
                'verbose_name': 'Document web',
                'verbose_name_plural': 'Documents web',
                'ordering': ['-created_at'],
            },
        ),
    ]
