# Generated by Django 5.1.6 on 2026-01-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0005_add_web_document_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationdata",
            name="droits_douane",
            field=models.CharField(
                blank=True,
                help_text="Taux de droits de douane (ex: 0%, 2.7%, Variable selon origine)",
                max_length=50,
                null=True,
                verbose_name="Droits de douane",
            ),
        ),
        migrations.AddField(
            model_name="classificationdata",
            name="tva",
            field=models.CharField(
                blank=True,
                default="20%",
                help_text="Taux de TVA applicable",
                max_length=20,
                null=True,
                verbose_name="TVA",
            ),
        ),
    ]
