# Generated by Django 5.1.6 on 2026-01-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0006_add_taxes_to_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsdata",
            name="cif_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="FOB + Fret + Assurance",
                max_digits=12,
                null=True,
                verbose_name="Valeur CIF",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_address",
            field=models.TextField(blank=True, verbose_name="Adresse du destinataire"),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ville du destinataire"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact chez le destinataire"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_country",
            field=models.CharField(
                blank=True,
                default="Algerie",
                max_length=100,
                verbose_name="Pays du destinataire",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_country_code",
            field=models.CharField(
                blank=True,
                default="DZ",
                max_length=2,
                verbose_name="Code pays destinataire (ISO)",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email destinataire"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_name",
            field=models.CharField(
                blank=True,
                help_text="Nom ou raison sociale du destinataire/importateur",
                max_length=255,
                verbose_name="Nom du destinataire",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Telephone destinataire"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code postal destinataire"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="consignee_tax_id",
            field=models.CharField(
                blank=True,
                help_text="NIF ou EORI du destinataire",
                max_length=50,
                verbose_name="ID fiscal destinataire",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="country_of_dispatch",
            field=models.CharField(
                blank=True,
                default="France",
                max_length=100,
                verbose_name="Pays d'expedition",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="country_of_dispatch_code",
            field=models.CharField(
                blank=True,
                default="FR",
                max_length=2,
                verbose_name="Code pays expedition (ISO)",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="country_of_origin",
            field=models.CharField(
                blank=True,
                default="France",
                max_length=100,
                verbose_name="Pays d'origine",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="country_of_origin_code",
            field=models.CharField(
                blank=True,
                default="FR",
                max_length=2,
                verbose_name="Code pays origine (ISO)",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="customs_procedure_code",
            field=models.CharField(
                blank=True,
                help_text="Ex: 10 00 (mise a la consommation)",
                max_length=10,
                verbose_name="Code regime douanier",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="customs_procedure_description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Description regime"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="expected_arrival_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'arrivee prevue"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="fob_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valeur FOB",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="form_completed",
            field=models.BooleanField(
                default=False, verbose_name="Formulaire complete"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="freight_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cout du fret",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="gross_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Poids brut (kg)",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="incoterms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW - Ex Works"),
                    ("FCA", "FCA - Free Carrier"),
                    ("CPT", "CPT - Carriage Paid To"),
                    ("CIP", "CIP - Carriage Insurance Paid"),
                    ("DAP", "DAP - Delivered At Place"),
                    ("DPU", "DPU - Delivered at Place Unloaded"),
                    ("DDP", "DDP - Delivered Duty Paid"),
                    ("FAS", "FAS - Free Alongside Ship"),
                    ("FOB", "FOB - Free On Board"),
                    ("CFR", "CFR - Cost and Freight"),
                    ("CIF", "CIF - Cost Insurance Freight"),
                ],
                default="CIF",
                max_length=3,
                verbose_name="Incoterms",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="incoterms_location",
            field=models.CharField(
                blank=True,
                help_text="Ex: CIF Alger, FOB Marseille",
                max_length=100,
                verbose_name="Lieu Incoterms",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="insurance_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cout de l'assurance",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="invoice_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EUR", "Euro (EUR)"),
                    ("DZD", "Dinar algerien (DZD)"),
                    ("USD", "Dollar americain (USD)"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="invoice_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de facture"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero de facture"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="invoice_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant total facture",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="net_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Poids net (kg)",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="number_of_packages",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de colis"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="package_type",
            field=models.CharField(
                blank=True,
                default="Carton",
                help_text="Ex: Carton, Palette, Caisse, Sac",
                max_length=50,
                verbose_name="Type d'emballage",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="port_of_discharge",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Port/aeroport de dechargement"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="port_of_loading",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Port/aeroport de chargement"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Quantite",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="statistical_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valeur statistique",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="transport_document_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date document transport"
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="transport_document_ref",
            field=models.CharField(
                blank=True,
                help_text="Numero du B/L, AWB, CMR, etc.",
                max_length=50,
                verbose_name="Reference document transport",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="transport_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BL", "Bill of Lading (B/L)"),
                    ("AWB", "Air Waybill (AWB)"),
                    ("CMR", "CMR (Route)"),
                    ("CIM", "CIM (Rail)"),
                ],
                max_length=30,
                verbose_name="Type de document transport",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="transport_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sea", "Maritime"),
                    ("air", "Aerien"),
                    ("road", "Routier"),
                    ("rail", "Ferroviaire"),
                    ("multimodal", "Multimodal"),
                ],
                max_length=20,
                verbose_name="Mode de transport",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="transport_mode_code",
            field=models.CharField(
                blank=True,
                help_text="1=Maritime, 2=Rail, 3=Route, 4=Air",
                max_length=1,
                verbose_name="Code mode transport",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="unit_of_measure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PCE", "Pieces (PCE)"),
                    ("KGM", "Kilogrammes (KGM)"),
                    ("MTR", "Metres (MTR)"),
                    ("LTR", "Litres (LTR)"),
                    ("MTQ", "Metres cubes (MTQ)"),
                    ("CTN", "Cartons (CTN)"),
                    ("PAL", "Palettes (PAL)"),
                ],
                default="PCE",
                max_length=20,
                verbose_name="Unite de mesure",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Prix unitaire",
            ),
        ),
        migrations.AddField(
            model_name="documentsdata",
            name="vessel_name",
            field=models.CharField(
                blank=True,
                help_text="Nom du navire ou numero de vol",
                max_length=100,
                verbose_name="Nom du navire/vol",
            ),
        ),
    ]
