# Generated by Django 5.2.6 on 2025-10-14 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sectors", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("pequeña", "Pequeña (1-50 empleados)"),
                            ("mediana", "Mediana (51-250 empleados)"),
                            ("grande", "Grande (250+ empleados)"),
                        ],
                        default="mediana",
                        max_length=20,
                    ),
                ),
                ("annual_revenue_eur", models.IntegerField(blank=True, null=True)),
                ("employees", models.IntegerField(blank=True, null=True)),
                ("years_in_business", models.IntegerField(blank=True, null=True)),
                (
                    "geographic_presence",
                    models.JSONField(default=list, help_text="NUTS regions"),
                ),
                ("technical_areas", models.JSONField(default=list)),
                ("programming_languages", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                ("certifications_technical", models.JSONField(default=list)),
                ("relevant_projects", models.JSONField(default=list)),
                ("public_sector_experience", models.BooleanField(default=False)),
                ("previous_clients", models.JSONField(default=list)),
                ("preferred_cpv_codes", models.JSONField(default=list)),
                ("preferred_contract_types", models.JSONField(default=list)),
                (
                    "budget_range",
                    models.JSONField(
                        default=dict,
                        help_text='{"min_eur": 200000, "max_eur": 3000000}',
                    ),
                ),
                ("preferred_regions", models.JSONField(default=list)),
                ("max_concurrent_bids", models.IntegerField(default=5)),
                ("avoid_keywords", models.JSONField(default=list)),
                ("main_competitors", models.JSONField(default=list)),
                ("competitive_advantages", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                (
                    "financial_capacity",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("buena", "Buena"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "team_availability",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("buena", "Buena"),
                            ("alta", "Alta"),
                        ],
                        default="buena",
                        max_length=20,
                    ),
                ),
                (
                    "overcommitment_risk",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="bajo",
                        max_length=20,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Empresa",
                "verbose_name_plural": "Perfiles de Empresas",
            },
        ),
    ]
