# Generated by Django 5.0.14 on 2025-11-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps_tenders", "0003_add_contact_fax_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tender",
            new_name="apps_tender_ojs_not_f0baea_idx",
            old_name="tenders_ten_ojs_not_55966b_idx",
        ),
        migrations.RenameIndex(
            model_name="tender",
            new_name="apps_tender_publica_15b7f5_idx",
            old_name="tenders_ten_publica_750081_idx",
        ),
        migrations.RenameIndex(
            model_name="tender",
            new_name="apps_tender_deadlin_4a1a23_idx",
            old_name="tenders_ten_deadlin_926963_idx",
        ),
        migrations.RenameIndex(
            model_name="tenderrecommendation",
            new_name="apps_tender_user_id_eda16d_idx",
            old_name="tenders_ten_user_id_86c1fb_idx",
        ),
    ]
