# Generated by Django 5.2.6 on 2025-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apps_authentication",
            "0002_user_address_line1_user_address_line2_user_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="llm_api_key",
            field=models.CharField(
                blank=True,
                help_text="Tu API key de Google Gemini u otro proveedor LLM",
                max_length=255,
                verbose_name="API Key del LLM",
            ),
        ),
    ]
