# Generated by Django 5.2.7 on 2025-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0003_user_llm_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='llm_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('nvidia', 'NVIDIA NIM')], default='gemini', help_text='Selecciona tu proveedor de IA preferido', max_length=20, verbose_name='Proveedor de IA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='llm_api_key',
            field=models.CharField(blank=True, help_text='Tu API key del proveedor seleccionado', max_length=255, verbose_name='API Key'),
        ),
    ]
