# Generated by Django 5.2.7 on 2025-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0004_user_llm_provider_alter_user_llm_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ollama_embedding_model',
            field=models.CharField(blank=True, default='nomic-embed-text', help_text='Modelo de embeddings para Ollama (ej: nomic-embed-text, mxbai-embed-large)', max_length=100, verbose_name='Modelo Embeddings Ollama'),
        ),
        migrations.AddField(
            model_name='user',
            name='ollama_model',
            field=models.CharField(blank=True, default='qwen2.5:72b', help_text='Modelo de chat para Ollama (ej: qwen2.5:72b, llama3.3:70b)', max_length=100, verbose_name='Modelo Ollama'),
        ),
        migrations.AlterField(
            model_name='user',
            name='llm_api_key',
            field=models.CharField(blank=True, help_text='Tu API key del proveedor seleccionado (no necesaria para Ollama)', max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='llm_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('nvidia', 'NVIDIA NIM'), ('ollama', 'Ollama (Local)')], default='gemini', help_text='Selecciona tu proveedor de IA preferido', max_length=20, verbose_name='Proveedor de IA'),
        ),
    ]
