# Generated by Django 5.2.6 on 2025-10-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apps_authentication",
            "0005_user_ollama_embedding_model_user_ollama_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_grading",
            field=models.BooleanField(
                default=False,
                help_text="Activa el filtrado de documentos irrelevantes (más preciso pero más lento)",
                verbose_name="Activar Grading",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="use_verification",
            field=models.BooleanField(
                default=False,
                help_text="Valida campos críticos con el XML original (más preciso pero más lento)",
                verbose_name="Activar Verificación XML",
            ),
        ),
    ]
