# Generated by Django 5.2.7 on 2025-11-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0006_user_use_grading_user_use_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openai_model',
            field=models.CharField(blank=True, choices=[('gpt-4o', 'GPT-4o (Más potente, más caro)'), ('gpt-4o-mini', 'GPT-4o-mini (Balance calidad/precio)'), ('gpt-4-turbo', 'GPT-4 Turbo (Anterior generación)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Económico, menos capaz)')], default='gpt-4o-mini', help_text='Modelo de chat para OpenAI (gpt-4o-mini recomendado)', max_length=50, verbose_name='Modelo OpenAI'),
        ),
    ]
