# Generated by Django 5.2.7 on 2025-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0007_user_openai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openai_embedding_model',
            field=models.CharField(blank=True, choices=[('text-embedding-3-small', 'text-embedding-3-small (Económico, recomendado)'), ('text-embedding-3-large', 'text-embedding-3-large (Más preciso, más caro)'), ('text-embedding-ada-002', 'text-embedding-ada-002 (Legacy)')], default='text-embedding-3-small', help_text='Modelo de embeddings para OpenAI (text-embedding-3-small recomendado)', max_length=100, verbose_name='Modelo Embeddings OpenAI'),
        ),
    ]
