# Generated by Django 5.0.14 on 2025-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_authentication", "0008_user_openai_embedding_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_search_api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key de Google Custom Search API",
                max_length=255,
                verbose_name="Google Search API Key",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_search_engine_id",
            field=models.CharField(
                blank=True,
                help_text="ID del motor de búsqueda personalizado (cx parameter)",
                max_length=100,
                verbose_name="Google Search Engine ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="use_web_search",
            field=models.BooleanField(
                default=False,
                help_text="Permite al agente buscar información actualizada en internet",
                verbose_name="Activar Búsqueda Web",
            ),
        ),
    ]
