# Generated by Django 5.0.14 on 2025-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_authentication", "0009_user_google_search_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="browse_max_chars",
            field=models.IntegerField(
                default=10000,
                help_text="Número máximo de caracteres a extraer de cada página web (1,000 - 50,000). Más caracteres = más tokens = mayor costo pero más información detallada.",
                verbose_name="Máximo de caracteres por página",
            ),
        ),
    ]
