# Generated by Django 5.0.14 on 2025-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_authentication", "0010_add_browse_max_chars"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="browse_chunk_size",
            field=models.IntegerField(
                default=1250,
                help_text="Número de caracteres por fragmento al analizar páginas (500 - browse_max_chars). Fragmentos más pequeños = más verificaciones pero mayor precisión. Aproximadamente 1 token = 4 caracteres.",
                verbose_name="Tamaño de fragmento de página",
            ),
        ),
    ]
