# Generated by Django 5.0.14 on 2025-11-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_authentication", "0011_add_browse_chunk_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_review_loops",
            field=models.IntegerField(
                default=3,
                help_text="Número máximo de veces que el sistema puede revisar y mejorar una respuesta (1-10). Default: 3. Más loops = mejor calidad pero más tiempo y tokens.",
                verbose_name="Máximo de loops de revisión",
            ),
        ),
    ]
