# Generated by Django 5.1.6 on 2026-01-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_authentication", "0012_user_max_review_loops"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="broker_contact",
            field=models.CharField(
                blank=True,
                help_text="Telephone ou email du transitaire",
                max_length=100,
                verbose_name="Contact transitaire",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="broker_customs_id",
            field=models.CharField(
                blank=True,
                help_text="Numero d'agrement douanier du transitaire",
                max_length=50,
                verbose_name="Code agrement transitaire",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="broker_name",
            field=models.CharField(
                blank=True,
                help_text="Nom du commissionnaire en douane",
                max_length=255,
                verbose_name="Nom du transitaire",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_legal_form",
            field=models.CharField(
                blank=True,
                help_text="Ex: SARL, SAS, EURL, SA",
                max_length=50,
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Raison sociale de l'entreprise",
                max_length=255,
                verbose_name="Nom de l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EUR", "Euro (EUR)"),
                    ("DZD", "Dinar algerien (DZD)"),
                    ("USD", "Dollar americain (USD)"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Devise par defaut",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_incoterms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW - Ex Works"),
                    ("FCA", "FCA - Free Carrier"),
                    ("CPT", "CPT - Carriage Paid To"),
                    ("CIP", "CIP - Carriage Insurance Paid"),
                    ("DAP", "DAP - Delivered At Place"),
                    ("DPU", "DPU - Delivered at Place Unloaded"),
                    ("DDP", "DDP - Delivered Duty Paid"),
                    ("FAS", "FAS - Free Alongside Ship"),
                    ("FOB", "FOB - Free On Board"),
                    ("CFR", "CFR - Cost and Freight"),
                    ("CIF", "CIF - Cost Insurance Freight"),
                ],
                default="CIF",
                max_length=3,
                verbose_name="Incoterms par defaut",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="eori_number",
            field=models.CharField(
                blank=True,
                help_text="Economic Operator Registration and Identification (EU) - Ex: FR12345678901234",
                max_length=17,
                verbose_name="Numero EORI",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nif_number",
            field=models.CharField(
                blank=True,
                help_text="Numero d'Identification Fiscale (Algerie)",
                max_length=20,
                verbose_name="NIF",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="siret_number",
            field=models.CharField(
                blank=True,
                help_text="Numero SIRET (France) - 14 chiffres",
                max_length=14,
                verbose_name="SIRET",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="Numero de TVA intracommunautaire - Ex: FR12345678901",
                max_length=20,
                verbose_name="Numero de TVA",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, default="France", max_length=100, verbose_name="País"
            ),
        ),
    ]
